###
GET http://localhost:3000/competition/

###
GET http://localhost:3000/competition/ranking/88327135-9e45-4e0d-af7b-b351e0082ff4

###
PUT http://localhost:3000/competition/status/88327135-9e45-4e0d-af7b-b351e0082ff4

###
POST http://localhost:3000/competition/create
Content-Type: application/json

{
    "name": "Nado Sicronizado"
}

###
POST http://localhost:3000/athletes/insert
Content-Type: application/json

{
    "idComp": "88327135-9e45-4e0d-af7b-b351e0082ff4",
    "name": "Jureval",
    "value": "4",
    "unity": "s"
}