###
// Puxar todas as competições
GET http://localhost:3000/competition/

###
GET http://localhost:3000/competition/ranking/6a32215a-31a5-4ec2-b78c-7718a16d7932

###
PUT http://localhost:3000/competition/status/6a32215a-31a5-4ec2-b78c-7718a16d7932

###
POST http://localhost:3000/competition/create
Content-Type: application/json

{
    "name": "lançamento de dardos Final"
}

###
POST http://localhost:3000/athletes/insert
Content-Type: application/json

{
    "idComp": "6a32215a-31a5-4ec2-b78c-7718a16d7932",
    "name": "chimpa",
    "value": "8",
    "unity": "m"
}