###
GET http://localhost:3003/user/profile/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNzcxNWM0LTc2NWMtNDVlMS05ZjExLTFlYTVkZDU5MWNjMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1NTg1MzgyNiwiZXhwIjoxNjU1ODUzODg2fQ.W-YJnGwYrWhrsuydCkzLONv62xZHLFABtcqMyqrDG0w
###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "babuino@email.com.br",
    "password": "123456",
    "role": "admin"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "babuino@email.com.br",
    "password": "123456"
}