###
GET http://localhost:3003/user/profile/
Authorization:
###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "orangotango@email.com.br",
    "password": "123456"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "orangotango@email.com.br",
    "password": "123456"
}