###
GET http://localhost:3003/post/find/001

###
GET http://localhost:3003/friend/feed/001

###
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Juvenal",
    "email": "Juvenal@email.com.br",
    "password": "12389536254jJ@"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "teste do 002", 
    "description": "teste do 002", 
    "type": "normal", 
    "authorId": "002"
}

###
POST http://localhost:3003/friend/create
Content-Type: application/json

{
    "userId": "001",
    "friendId": "c1d5fd36-7bb5-4299-81e9-5d044a51c807"
}

###
DELETE http://localhost:3003/friend/delete
Content-Type: application/json

{
    "userId": "c1d5fd36-7bb5-4299-81e9-5d044a51c807",
    "friendId": "001"
}